language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
deploy:
  - provider: surge
    skip_cleanup: true
    domain: votoinformado2019.com
    project: ./build/
    on:
      branch: master
  - provider: surge
    skip_cleanup: true
    domain: vmain-staging.surge.sh
    project: ./build/
    on:
      branch: staging
