export const GET_MORE_RELATED_INSTANCES = { // eslint-disable-line
  INIT: 'GET_MORE_RELATED_INSTANCES_INIT',
  REQUEST: 'GET_MORE_RELATED_INSTANCES_REQUEST',
  SUCCESS: 'GET_MORE_RELATED_INSTANCES_SUCCESS',
  ERROR: 'GET_MORE_RELATED_INSTANCES_ERROR',
};
