export const GET_MORE_RELATED_INSTANCES = {
  INIT: 'GET_MORE_RELATED_INSTANCES_INIT',
  REQUEST: 'GET_MORE_RELATED_INSTANCES_REQUEST',
  SUCCESS: 'GET_MORE_RELATED_INSTANCES_SUCCESS',
  ERROR: 'GET_MORE_RELATED_INSTANCES_ERROR',
};


export const INSTANCE_DETAIL = 'INSTANCE_DETAIL';


export const TOGGLE_INSTANCE_DETAIL_MODAL = 'TOGGLE_INSTANCE_DETAIL_MODAL';
