// Related Individuals according to parent container
export const GET_RELATED_FINANCE_ITEMS = {
  REQUEST: 'GET_RELATED_FINANCE_ITEMS_REQUEST',
  SUCCESS: 'GET_RELATED_FINANCE_ITEMS_SUCCESS',
  ERROR: 'GET_RELATED_FINANCE_ITEMS_ERROR',
};

export const GET_CORRUPTION_FUNDS = {
  REQUEST: 'GET_CORRUPTION_FUNDS_REQUEST',
  SUCCESS: 'GET_CORRUPTION_FUNDS_SUCCESS',
  ERROR: 'GET_CORRUPTION_FUNDS_ERROR',
};

export const GET_NON_CORRUPTION_FUNDS = {
  REQUEST: 'GET_NON_CORRUPTION_FUNDS_REQUEST',
  SUCCESS: 'GET_NON_CORRUPTION_FUNDS_SUCCESS',
  ERROR: 'GET_NON_CORRUPTION_FUNDS_ERROR',
};

export const GET_ALL_FUNDS = {
  REQUEST: 'GET_ALL_FUNDS_REQUEST',
  SUCCESS: 'GET_ALL_FUNDS_SUCCESS',
  ERROR: 'GET_ALL_FUNDS_ERROR',
};
