// Basically the pagination action for the recent news
export const GET_RECENT_INFORMATIVE_SNIPPETS = {
  REQUEST: 'GET_RECENT_INFORMATIVE_SNIPPETS_REQUEST',
  SUCCESS: 'GET_RECENT_INFORMATIVE_SNIPPETS_SUCCESS',
  ERROR: 'GET_RECENT_INFORMATIVE_SNIPPETS_ERROR',
};

// Related informative Snippets according to parent container
export const GET_RELATED_INFORMATIVE_SNIPPETS = {
  REQUEST: 'GET_RELATED_INFORMATIVE_SNIPPETS_REQUEST',
  SUCCESS: 'GET_RELATED_INFORMATIVE_SNIPPETS_SUCCESS',
  ERROR: 'GET_RELATED_INFORMATIVE_SNIPPETS_ERROR',
};
