// ----------- PAGE -------------
export const GET_DETAILED_CORRUPTION_CASE_PAGE = {
  INIT: 'GET_DETAILED_CORRUPTION_CASE_PAGE_INIT',
  REQUEST: 'GET_DETAILED_CORRUPTION_CASE_PAGE_REQUEST',
  SUCCESS: 'GET_DETAILED_CORRUPTION_CASE_PAGE_SUCCESS',
  ERROR: 'GET_DETAILED_CORRUPTION_CASE_PAGE_ERROR',
};

// ----------- RELATIONSHIPS -------------
// Related Individuals according to parent container
export const GET_RELATED_CORRUPTION_CASES = {
  INIT: 'GET_RELATED_CORRUPTION_CASES_INIT',
  REQUEST: 'GET_RELATED_CORRUPTION_CASES_REQUEST',
  SUCCESS: 'GET_RELATED_CORRUPTION_CASES_SUCCESS',
  ERROR: 'GET_RELATED_CORRUPTION_CASES_ERROR',
};
