// TODO: Devise namespacing system for all redux actions
export const GET_KNOWLEDGE_BASE_FEED = {
  INIT: 'GET_KNOWLEDGE_BASE_FEED_INIT',
  REQUEST: 'GET_KNOWLEDGE_BASE_FEED_REQUEST',
  SUCCESS: 'GET_KNOWLEDGE_BASE_FEED_SUCCESS',
  ERROR: 'GET_KNOWLEDGE_BASE_FEED_ERROR',
};


export const SEARCH_KNOWLEDGE_BASE = {
  INIT: 'SEARCH_KNOWLEDGE_BASE_INIT',
  REQUEST: 'SEARCH_KNOWLEDGE_BASE_REQUEST',
  SUCCESS: 'SEARCH_KNOWLEDGE_BASE_SUCCESS',
  ERROR: 'SEARCH_KNOWLEDGE_BASE_ERROR',
};


export const GET_KNOWLEDGE_BASE_DETAIL = {
  INIT: 'GET_KNOWLEDGE_BASE_DETAIL_INIT',
  REQUEST: 'GET_KNOWLEDGE_BASE_DETAIL_REQUEST',
  SUCCESS: 'GET_KNOWLEDGE_BASE_DETAIL_SUCCESS',
  ERROR: 'GET_KNOWLEDGE_BASE_DETAIL_ERROR',
};
