export const CHANGE_MAP_VIEWPORT = 'CHANGE_MAP_VIEWPORT';


export const GET_MAP_DATA = {
  INIT: 'GET_MAP_DATA_INIT',
  REQUEST: 'GET_MAP_DATA_REQUEST',
  SUCCESS: 'GET_MAP_DATA_SUCCESS',
  ERROR: 'GET_MAP_DATA_ERROR',
};
