export const GET_HOME = {
  INIT: 'GET_HOME_INIT',
  REQUEST: 'GET_HOME_REQUEST',
  SUCCESS: 'GET_HOME_SUCCESS',
  ERROR: 'GET_HOME_ERROR',
};


export const SUGGEST = {
  INIT: 'SUGGEST_INIT',
  REQUEST: 'SUGGEST_REQUEST',
  SUCCESS: 'SUGGEST_SUCCESS',
  ERROR: 'SUGGEST_ERROR',
};


export const SEARCH = {
  INIT: 'SEARCH_INIT',
  REQUEST: 'SEARCH_REQUEST',
  SUCCESS: 'SEARCH_SUCCESS',
  ERROR: 'SEARCH_ERROR',
};


export const INCREMENT_SEARCH_PAGE = 'INCREMENT_HOME_SEARCH_PAGE';


export const SUBSCRIBED_STATS = {
  INIT: 'SUBSCRIBED_STATS_INIT',
  REQUEST: 'SUBSCRIBED_STATS_REQUEST',
  SUCCESS: 'SUBSCRIBED_STATS_SUCCESS',
  ERROR: 'SUBSCRIBED_STATS_ERROR',
};


export const DISCOVER_CANDIDATES = {
  INIT: 'DISCOVER_CANDIDATES_INIT',
  REQUEST: 'DISCOVER_CANDIDATES_REQUEST',
  SUCCESS: 'DISCOVER_CANDIDATES_SUCCESS',
  ERROR: 'DISCOVER_CANDIDATES_ERROR',
};
