export const GET_HOME = {
  INIT: 'GET_HOME_INIT',
  REQUEST: 'GET_HOME_REQUEST',
  SUCCESS: 'GET_HOME_SUCCESS',
  ERROR: 'GET_HOME_ERROR',
};


export const HOME_SEARCH = {
  INIT: 'HOME_SEARCH_INIT',
  REQUEST: 'HOME_SEARCH_REQUEST',
  SUCCESS: 'HOME_SEARCH_SUCCESS',
  ERROR: 'HOME_SEARCH_ERROR',
};
