export const GET_HOME = {
  INIT: 'GET_HOME_INIT',
  REQUEST: 'GET_HOME_REQUEST',
  SUCCESS: 'GET_HOME_SUCCESS',
  ERROR: 'GET_HOME_ERROR',
};

// TODO NOT HAPPENING
// export const HOME_SEARCH = {
//   INIT: 'HOME_SEARCH_INIT',
//   REQUEST: 'HOME_SEARCH_REQUEST',
//   SUCCESS: 'HOME_SEARCH_SUCCESS',
//   ERROR: 'HOME_SEARCH_ERROR',
// };

export const SUBSCRIBED_STATS = {
  INIT: 'SUBSCRIBED_STATS_INIT',
  REQUEST: 'SUBSCRIBED_STATS_REQUEST',
  SUCCESS: 'SUBSCRIBED_STATS_SUCCESS',
  ERROR: 'SUBSCRIBED_STATS_ERROR',
};

export const DISCOVER_CANDIDATES = {
  INIT: 'DISCOVER_CANDIDATES_INIT',
  REQUEST: 'DISCOVER_CANDIDATES_REQUEST',
  SUCCESS: 'DISCOVER_CANDIDATES_SUCCESS',
  ERROR: 'DISCOVER_CANDIDATES_ERROR',
};
